name: 'Setup nodejs'

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build demo and deploy it to gh-pages

    steps:
      - name: Checkout sources
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0

      - name: Set up Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d #v3.8.1
        with:
          node-version: '20'

      - name: Install
        run: |
          npm install --frozen-lockfile
          npm run build

      - name: Commit demo for gh-pages
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772 #v1.4
        with:
          directory: './build'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'doc: update demo'
          branch: main
